### ISSUE TITLE
Update deprecated code

### ISSUE THREAD

**Issue by GabryDX** [druzsan/justetf-scraping#12]
When executing the command `justetf_scraping.load_overview()` I get:

```
FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[column] = df[column].replace({"Yes": True, "No": False}).astype("bool")
```

Everything works so it is not blocking, but needs to be addressed.

**Comment by druzsan** [comment]
The problem was that my Pandas version is too low (`2.0.3`) because of Python 3.8 support.

The warning itself is addressed e.g. [here](https://github.com/pandas-dev/pandas/issues/57734) and the suggested solution is to disable the future warning `pd.set_option('future.no_silent_downcasting', True)` somewhere before `justetf_scraping.load_overview()`.
